export default {
  hai: {
    '1m': '/img/hai/1m.gif',
    '2m': '/img/hai/2m.gif',
    '3m': '/img/hai/3m.gif',
    '4m': '/img/hai/4m.gif',
    '5m': '/img/hai/5m.gif',
    '6m': '/img/hai/6m.gif',
    '7m': '/img/hai/7m.gif',
    '8m': '/img/hai/8m.gif',
    '9m': '/img/hai/9m.gif',
    '1p': '/img/hai/1p.gif',
    '2p': '/img/hai/2p.gif',
    '3p': '/img/hai/3p.gif',
    '4p': '/img/hai/4p.gif',
    '5p': '/img/hai/5p.gif',
    '6p': '/img/hai/6p.gif',
    '7p': '/img/hai/7p.gif',
    '8p': '/img/hai/8p.gif',
    '9p': '/img/hai/9p.gif',
    '1s': '/img/hai/1s.gif',
    '2s': '/img/hai/2s.gif',
    '3s': '/img/hai/3s.gif',
    '4s': '/img/hai/4s.gif',
    '5s': '/img/hai/5s.gif',
    '6s': '/img/hai/6s.gif',
    '7s': '/img/hai/7s.gif',
    '8s': '/img/hai/8s.gif',
    '9s': '/img/hai/9s.gif',
    'a': '/img/hai/a.gif',
    'b': '/img/hai/b.gif',
    'c': '/img/hai/c.gif',
    'd': '/img/hai/d.gif',
    'e': '/img/hai/e.gif',
    'f': '/img/hai/f.gif',
    'g': '/img/hai/g.gif',
    'a5m': '/img/hai/a5m.png',
    'a5p': '/img/hai/a5p.png',
    'a5s': '/img/hai/a5s.png',
  },
};

